[2024-11-25T16:51:15.893+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_company_data.print_data__1 manual__2024-11-25T16:51:10.884059+00:00 [queued]>
[2024-11-25T16:51:15.900+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_company_data.print_data__1 manual__2024-11-25T16:51:10.884059+00:00 [queued]>
[2024-11-25T16:51:15.900+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-25T16:51:15.905+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): print_data__1> on 2024-11-25 16:51:10.884059+00:00
[2024-11-25T16:51:15.907+0000] {standard_task_runner.py:60} INFO - Started process 194 to run task
[2024-11-25T16:51:15.909+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_company_data', 'print_data__1', 'manual__2024-11-25T16:51:10.884059+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/migrate_company_dag.py', '--cfg-path', '/tmp/tmp8zzhb9wr']
[2024-11-25T16:51:15.909+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask print_data__1
[2024-11-25T16:51:15.928+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_company_data.print_data__1 manual__2024-11-25T16:51:10.884059+00:00 [running]> on host 3097ba3c96d3
[2024-11-25T16:51:15.954+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'print_data__1', field 'op_args'. Template: (XComArg(<Task(_PythonDecoratedOperator): map_to_company_information_list>),)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 180, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 180, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 176, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 417, in resolve
    result = ti.xcom_pull(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3090, in xcom_pull
    return XCom.deserialize_value(first)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 694, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 689, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 117, in object_hook
    return deserialize(dct)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 254, in deserialize
    raise ImportError(
ImportError: models.migrate_company_model.CompanyInformation was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-11-25T16:51:15.954+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2360, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2498, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2910, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 180, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 180, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 176, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 417, in resolve
    result = ti.xcom_pull(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3090, in xcom_pull
    return XCom.deserialize_value(first)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 694, in deserialize_value
    return BaseXCom._deserialize_value(result, False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 689, in _deserialize_value
    return json.loads(result.value.decode("UTF-8"), cls=XComDecoder, object_hook=object_hook)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 117, in object_hook
    return deserialize(dct)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 254, in deserialize
    raise ImportError(
ImportError: models.migrate_company_model.CompanyInformation was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration
[2024-11-25T16:51:15.958+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=migrate_company_data, task_id=print_data__1, execution_date=20241125T165110, start_date=20241125T165115, end_date=20241125T165115
[2024-11-25T16:51:15.962+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task print_data__1 (models.migrate_company_model.CompanyInformation was not found in allow list for deserialization imports. To allow it, add it to allowed_deserialization_classes in the configuration; 194)
[2024-11-25T16:51:16.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-25T16:51:16.015+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
