[2024-11-22T10:10:12.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:10:11.617204+00:00 [queued]>
[2024-11-22T10:10:12.278+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:10:11.617204+00:00 [queued]>
[2024-11-22T10:10:12.278+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-22T10:10:12.283+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): query_company_security> on 2024-11-22 10:10:11.617204+00:00
[2024-11-22T10:10:12.285+0000] {standard_task_runner.py:60} INFO - Started process 231 to run task
[2024-11-22T10:10:12.286+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_company_data', 'query_company_security', 'manual__2024-11-22T10:10:11.617204+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/migrate_company_dag.py', '--cfg-path', '/tmp/tmptuecn652']
[2024-11-22T10:10:12.287+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask query_company_security
[2024-11-22T10:10:12.309+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:10:11.617204+00:00 [running]> on host d91947755a51
[2024-11-22T10:10:12.339+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Au Pakin' AIRFLOW_CTX_DAG_ID='migrate_company_data' AIRFLOW_CTX_TASK_ID='query_company_security' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T10:10:11.617204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T10:10:11.617204+00:00'
[2024-11-22T10:10:12.346+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/migrate_company_task.py", line 16, in query_company_security
    with hook.get_conn() as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 187, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_sql_exchange_conn` isn't defined
[2024-11-22T10:10:12.347+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=migrate_company_data, task_id=query_company_security, execution_date=20241122T101011, start_date=20241122T101012, end_date=20241122T101012
[2024-11-22T10:10:12.351+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task query_company_security (The conn_id `my_sql_exchange_conn` isn't defined; 231)
[2024-11-22T10:10:12.386+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T10:10:12.396+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
