[2024-11-22T10:20:56.783+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:20:56.326456+00:00 [queued]>
[2024-11-22T10:20:56.787+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:20:56.326456+00:00 [queued]>
[2024-11-22T10:20:56.788+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-22T10:20:56.793+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): query_company_security> on 2024-11-22 10:20:56.326456+00:00
[2024-11-22T10:20:56.796+0000] {standard_task_runner.py:60} INFO - Started process 183 to run task
[2024-11-22T10:20:56.798+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_company_data', 'query_company_security', 'manual__2024-11-22T10:20:56.326456+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/migrate_company_dag.py', '--cfg-path', '/tmp/tmppxfmi5iu']
[2024-11-22T10:20:56.798+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask query_company_security
[2024-11-22T10:20:56.826+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_company_data.query_company_security manual__2024-11-22T10:20:56.326456+00:00 [running]> on host 08acbfba0d4c
[2024-11-22T10:20:56.862+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Au Pakin' AIRFLOW_CTX_DAG_ID='migrate_company_data' AIRFLOW_CTX_TASK_ID='query_company_security' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T10:20:56.326456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T10:20:56.326456+00:00'
[2024-11-22T10:20:56.867+0000] {base.py:83} INFO - Using connection ID 'my_sql_exchange_conn' for task execution.
[2024-11-22T10:20:56.878+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/migrate_company_task.py", line 16, in query_company_security
    with hook.get_conn() as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.4' (using ***: YES)")
[2024-11-22T10:20:56.881+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=migrate_company_data, task_id=query_company_security, execution_date=20241122T102056, start_date=20241122T102056, end_date=20241122T102056
[2024-11-22T10:20:56.886+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task query_company_security ((1045, "Access denied for user 'root'@'172.18.0.4' (using ***: YES)"); 183)
[2024-11-22T10:20:56.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-22T10:20:56.910+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
